languageCode = "en-us"
title = "Section"
copyright = ""
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
paginate = 5
disableKinds = [ "taxonomyTerm" ]
ignorefiles = [ "blog/tag/.*", "videos/category/.*" ]
pygmentsCodeFences = true
pygmentsStyle = "monokai"
[taxonomies]
   tag = "tags"
   category = "categories"
   topic = "topics"
   author = "author"
[permalinks]
   tags = "/blog/tag/:slug/"
   categories = "/videos/category/:slug/"
   engineering-education = "/:sections/:slug"
   topics = "/engineering-education/topic/:slug/"
[author]
  name = "Molly Wojcek"
  email = "molly@section.io"
[params]
  dateformat = "January 2, 2006"
  description = "Section's Edge as a Service simplifies edge computing for next-gen applications."
[markup.goldmark.renderer]
  unsafe = true
[social]
email = "support@forestry.io"
slack = "https://t.co/OANAJYol8Y"
twitter = "https://twitter.com/sectionio"
facebook = "https://www.facebook.com/sectionio/"
github = "https://github.com/section-io/"
[blackfriday]
  plainIDAnchors = true
[related]
threshold = 80
includeNewer = true
toLower = false
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "tags"
weight = 80
[[related.indices]]
name  = "categories"
weight = 80
[[related.indices]]
name  = "topics"
weight = 80
[[related.indices]]
name  = "date"
weight = 10